(in-package :metis)



(defun manardb-recreate-tables ()
  (manardb:defmmclass additionalEventData ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass awsRegion ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass errorCode ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass errorMessage ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventID ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventName ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventSource ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventTime ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventType ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass eventVersion ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass recipientAccountId ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass requestID ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass requestParameters ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass resources ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass responseElements ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass sourceIPAddress ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass userAgent ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass userIdentity ()
    ((value :type STRING :initarg :value)))
  (manardb:defmmclass userName ()
    ((value :type STRING :initarg :value)))
  )

(defun manardb-normalize-insert (record)
  (format t "manardb-nomalize-insert ~A~%" record)
  )

(defun manardb-get-or-insert-id (table value)
  (format t "manard-get-or-insert-id table:~A value:~A~%" table value)
  )

(defun manardb-drop-table (query)
  (format t "manardb-drop-table query:~A~%" query)
  )
