(in-package :metis)


(manardb:defmmclass ct ()
   ((additionalEventData :type STRING :initarg :additionalEventData)
   (awsRegion :type STRING :initarg :awsRegion)
   (errorCode :type STRING :initarg :errorCode)
   (errorMessage :type STRING :initarg :errorMessage)
   (eventID :type STRING :initarg :eventID)
   (eventName :type STRING :initarg :eventName)
   (eventSource :type STRING :initarg :eventSource)
   (eventTime :type STRING :initarg :eventTime)
   (eventType :type STRING :initarg :eventType)
   (eventVersion :type STRING :initarg :eventVersion)
   (recipientAccountId :type STRING :initarg :recipientAccountId)
   (requestID :type STRING :initarg :requestID)
   (requestParameters :type STRING :initarg :requestParameters)
   (resources :type STRING :initarg :resources)
   (responseElements :type STRING :initarg :responseElements)
   (sourceIPAddress :type STRING :initarg :sourceIPAddress)
   (userAgent :type STRING :initarg :userAgent)
   (userIdentity :type STRING :initarg :userIdentity)
   (userName :type STRING :initarg :userName)))

(defun manardb-recreate-tables ()
  (format t "manardb-recreate-tables~%"))

(defun manardb-normalize-insert (record)
  (format t "manardb-nomalize-insert ~A~%" record)
  )

(defun manardb-get-or-insert-id (table value)
  (format t "manard-get-or-insert-id table:~A value:~A~%" table value)
  )

(defun manardb-drop-table (query)
  (format t "manardb-drop-table query:~A~%" query)
  )
