#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#
(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp(ql:quickload :metis :silent t)
  )

(defpackage :ros.script.metis.3743451485
  (:use :cl))
(in-package :ros.script.metis.3743451485)

(defun main (&rest argv)
  (declare (ignorable argv))
  (apply #'metis:main argv))
;;; vim: set ft=lisp lisp:
