(defun leveldb/close ()  )
(defun leveldb/db-do-query (query))
(defun leveldb/db-recreate-tables ())
(defun leveldb/drop-table ())
(defun leveldb/get-or-insert-id (table value))
(defun leveldb/have-we-seen-this-file (file))
(defun leveldb/init () )
(defun leveldb/mark-file-processed (file))
(defun leveldb/normalize-insert (db file))
