;(setf excl:*tenured-bytes-limit* 52428800)
(setq excl:*global-gc-behavior* nil)
(setq excl:*load-source-file-info* nil)
(setq excl:*load-xref-info* nil)
(setq excl:*record-source-file-info* nil)
(setq excl:*record-xref-info* nil)
;;(setf excl:*global-gc-behavior* :auto)
