#-cmucl (load "~/quicklisp/setup.lisp")
(ql:quickload '(:fare-memoization :cl-fad :gzip-stream :cl-json :pcall :rucksack))

(princ "pkgdcl")
(load (compile-file "pkgdcl.lisp"))
(princ "database")
(load (compile-file "collector/database.lisp"))
;; (princ "rucksack")
;; (load (compile-file "collector/rucksack.lisp"))
(princ "utils")
(load (compile-file "collector/utils.lisp"))
(princ "ctcl")
(load (compile-file "collector/ctcl.lisp"))
(princ "main")
(load (compile-file "collector/main.lisp"))
(in-package :ctcl)
